image: node:16
stages:
  - test

local_integration_test:
  stage: test
  image: registry.gitlab.com/gitlab-ci-utils/docker-puppeteer:node-16
    - npm install
    - npm run test:build
    - npm run test:mocha
  
  when: always
  allow_failure: false
