image: node:14
stages:
  - test

local_integration_test:
  stage: test
  image: registry.gitlab.com/gitlab-ci-utils/docker-puppeteer:node-14
  script:
    - npm install
    - npm run build
    - npm run test-mocha
  
  when: manual
  allow_failure: false
